"""Create bakeries and baked_goods tables

Revision ID: d9843e93ab70
Revises: b6aec9715b77
Create Date: 2025-06-16 23:17:08.165750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9843e93ab70'
down_revision = 'b6aec9715b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
